language: bash

notifications:
  email: false

env:
  REST_SERVER_VER=1.14 DOCKER_IMAGE=ingvord/tango-cs-with-rest

services:
  - docker

script:
  - docker build --build-arg REST_SERVER_VER=${REST_SERVER_VER} -t ${DOCKER_IMAGE} .

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag ${DOCKER_IMAGE} ingvord/${DOCKER_IMAGE}:${TRAVIS_BRANCH}

deploy:
  - provider: script
    script: docker push ${DOCKER_IMAGE}:latest
    on:
      all_branches: true
  - provider: script
    script: docker push ${DOCKER_IMAGE}:${TRAVIS_TAG}
    on:
      tags: true